window.FEATURE_DATA = [
  { d:'AUTH', id:'AUTH-01', f:'登录/登出/注册/重置', r:'/app/login + auth API', rule:'认证流程与多租户上下文切换', fe:'/app/javascript/v3/views/routes.js', be:'/config/routes.rb' },
  { d:'CONV', id:'CONV-D01', f:'会话状态与优先级枚举', r:'/api/v1/accounts/:id/conversations', rule:'status=open/resolved/pending/snoozed; priority=low/medium/high/urgent', fe:'/app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js', be:'/app/models/conversation.rb:75' },
  { d:'CONV', id:'CONV-D02', f:'新会话默认状态判定', r:'conversation create', rule:'blocked->resolved; active_bot->pending; campaign+bot->pending', fe:'/app/javascript/dashboard/routes/dashboard/conversation', be:'/app/models/conversation.rb:254' },
  { d:'CONV', id:'CONV-D03', f:'toggle_status 语义', r:'POST toggle_status', rule:'open<->resolved, pending/snoozed->open', fe:'/app/javascript/dashboard/store/modules/conversations', be:'/app/models/conversation.rb:149' },
  { d:'CONV', id:'CONV-D04', f:'last_seen 节流', r:'POST update_last_seen', rule:'无未读时按小时节流写入', fe:'/app/javascript/dashboard', be:'/app/controllers/api/v1/accounts/conversations_controller.rb:114' },
  { d:'CRM', id:'CRM-D01', f:'联系人类型与唯一性', r:'/api/v1/accounts/:id/contacts', rule:'visitor/lead/customer; email/phone/identifier 约束', fe:'/app/javascript/dashboard/routes/dashboard/contacts/routes.js', be:'/app/models/contact.rb:50' },
  { d:'CRM', id:'CRM-D02', f:'联系人事件派发', r:'contact lifecycle events', rule:'create/update/delete 均派发 dispatcher', fe:'/app/javascript/dashboard', be:'/app/models/contact.rb:235' },
  { d:'INBOX', id:'INBOX-D01', f:'渠道识别与行为', r:'/api/v1/accounts/:id/inboxes', rule:'web/api/email/sms/whatsapp/social 分型', fe:'/app/javascript/dashboard/routes/dashboard/settings/inbox/inbox.routes.js', be:'/app/models/inbox.rb:113' },
  { d:'INBOX', id:'INBOX-D02', f:'active_bot 判定', r:'conversation bootstrap', rule:'agent_bot_active 或 dialogflow hook enabled', fe:'/app/javascript/dashboard', be:'/app/models/inbox.rb:169' },
  { d:'INBOX', id:'INBOX-D03', f:'可分配坐席集合', r:'assignable agents', rule:'inbox members + account admins', fe:'/app/javascript/dashboard/components', be:'/app/models/inbox.rb:165' },
  { d:'AUTO', id:'AUTO-D01', f:'自动化条件白名单', r:'/api/v1/accounts/:id/automation_rules', rule:'conditions_attributes + 自定义属性', fe:'/app/javascript/dashboard/routes/dashboard/settings/automation', be:'/app/models/automation_rule.rb:37' },
  { d:'AUTO', id:'AUTO-D02', f:'自动化动作白名单', r:'automation actions', rule:'仅允许定义动作集合', fe:'/app/javascript/dashboard', be:'/app/models/automation_rule.rb:42' },
  { d:'AUTO', id:'AUTO-D03', f:'逻辑运算符校验', r:'automation conditions', rule:'query_operator 仅 AND/OR', fe:'/app/javascript/dashboard', be:'/app/models/automation_rule.rb:91' },
  { d:'AUTO', id:'AUTO-D04', f:'Macro 可见性与执行权限', r:'/api/v1/accounts/:id/macros', rule:'personal/global + author/admin 策略', fe:'/app/javascript/dashboard/routes/dashboard/settings/macros', be:'/app/models/macro.rb:29 + /app/policies/macro_policy.rb:10' },
  { d:'CMP', id:'CMP-D01', f:'Campaign 类型约束', r:'/api/v1/accounts/:id/campaigns', rule:'仅 Website/Twilio SMS/Sms/Whatsapp', fe:'/app/javascript/dashboard/routes/dashboard/campaigns/campaigns.routes.js', be:'/app/models/campaign.rb:81' },
  { d:'CMP', id:'CMP-D02', f:'ongoing/one_off 推导', r:'campaign create/update', rule:'Website=ongoing; SMS/Twilio/Whatsapp=one_off', fe:'/app/javascript/dashboard/components-next/Campaigns', be:'/app/models/campaign.rb:88' },
  { d:'CMP', id:'CMP-D03', f:'URL 校验规则', r:'live chat campaign', rule:'Website campaign URL 必须 http/https', fe:'/app/javascript/dashboard/components-next/Campaigns', be:'/app/models/campaign.rb:100' },
  { d:'CMP', id:'CMP-D04', f:'Widget 触发链路', r:'/api/v1/widget/campaigns + /events', rule:'曝光匹配后发 campaign.triggered 建会话', fe:'/app/javascript/widget/api/endPoints.js:79', be:'/app/listeners/campaign_listener.rb:2' },
  { d:'HC', id:'HC-D01', f:'Portal 基础约束', r:'/api/v1/accounts/:id/portals', rule:'name/slug/account 必填；slug/custom_domain 唯一', fe:'/app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js', be:'/app/models/portal.rb:39' },
  { d:'HC', id:'HC-D02', f:'Article 状态机与语言继承', r:'/api/v1/accounts/:id/articles', rule:'draft/published/archived + locale 继承', fe:'/app/javascript/dashboard/routes/dashboard/helpcenter', be:'/app/models/article.rb:67' },
  { d:'ACL', id:'ACL-D01', f:'默认拒绝策略', r:'all policies', rule:'ApplicationPolicy 默认 create/update/destroy=false', fe:'N/A', be:'/app/policies/application_policy.rb:12' },
  { d:'ACL', id:'ACL-D02', f:'会话可见范围', r:'conversation show/index', rule:'admin 全量；agent 需 inbox/team 访问', fe:'/app/javascript/dashboard', be:'/app/policies/conversation_policy.rb:10' },
  { d:'ACL', id:'ACL-D03', f:'联系人高危操作限权', r:'contact import/export/destroy', rule:'管理员专属', fe:'/app/javascript/dashboard/routes/dashboard/contacts', be:'/app/policies/contact_policy.rb:10' },
  { d:'ASYNC', id:'ASYNC-D01', f:'定时触发计划项', r:'trigger_scheduled_items_job', rule:'每 5 分钟执行', fe:'N/A', be:'/config/schedule.yml:11' },
  { d:'ASYNC', id:'ASYNC-D02', f:'IMAP 拉取任务', r:'trigger_imap_email_inboxes_job', rule:'每 1 分钟执行', fe:'N/A', be:'/config/schedule.yml:17' },
  { d:'ASYNC', id:'ASYNC-D03', f:'自动分配任务', r:'bulk_auto_assignment + periodic_assignment', rule:'每 15/30 分钟执行', fe:'N/A', be:'/config/schedule.yml:51' },
  { d:'ASYNC', id:'ASYNC-D04', f:'清理任务', r:'notification/orphan/stale cleanup', rule:'按 cron 执行运维清理', fe:'N/A', be:'/config/schedule.yml:24' }
];

window.SCREENSHOT_DATA = [
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/campaigns.png", title: "campaigns", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-assistants.png", title: "captain assistants", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-documents.png", title: "captain documents", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-guardrails.png", title: "captain guardrails", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-guidelines.png", title: "captain guidelines", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-inboxes.png", title: "captain inboxes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-playground.png", title: "captain playground", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-responses.png", title: "captain responses", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-scenarios.png", title: "captain scenarios", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-settings.png", title: "captain settings", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-tools.png", title: "captain tools", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/contacts.png", title: "contacts", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-folder-filter.png", title: "conversation folder filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-inbox-filter.png", title: "conversation inbox filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-label-filter.png", title: "conversation label filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-participating.png", title: "conversation participating", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-team-filter.png", title: "conversation team filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/dashboard.png", title: "dashboard", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-01-list.png", title: "campaign livechat 01 list", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-02-created-list.png", title: "campaign livechat 02 created list", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-03-form-fields.png", title: "campaign livechat 03 form fields", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-list-before-create.png", title: "campaign livechat list before create", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-ongoing.png", title: "campaigns ongoing", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-sms.png", title: "campaigns sms", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-whatsapp.png", title: "campaigns whatsapp", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/companies.png", title: "companies", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-articles.png", title: "helpcenter aaa articles", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-categories.png", title: "helpcenter aaa categories", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-locales.png", title: "helpcenter aaa locales", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-public-home.png", title: "helpcenter aaa public home", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-settings.png", title: "helpcenter aaa settings", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/reports-bot.png", title: "reports bot", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/reports-overview.png", title: "reports overview", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-canned-new.png", title: "settings canned new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-captain.png", title: "settings captain", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-conversation-workflow.png", title: "settings conversation workflow", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-inbox-show.png", title: "settings inbox show", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-dashboard-apps.png", title: "settings integrations dashboard apps", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-linear.png", title: "settings integrations linear", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-notion.png", title: "settings integrations notion", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-shopify.png", title: "settings integrations shopify", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-slack.png", title: "settings integrations slack", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-webhook.png", title: "settings integrations webhook", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-macros-new.png", title: "settings macros new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-profile-mfa.png", title: "settings profile mfa", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-sla.png", title: "settings sla", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-teams-new.png", title: "settings teams new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/help-center.png", title: "help center", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/inbox-view.png", title: "inbox view", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-livechat.png", title: "campaigns livechat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-ongoing.png", title: "campaigns ongoing", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-sms.png", title: "campaigns sms", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-whatsapp.png", title: "campaigns whatsapp", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-livechat.png", title: "click campaign tab livechat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-sms.png", title: "click campaign tab sms", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-whatsapp-failed.png", title: "click campaign tab whatsapp failed", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-new-campaign-button-failed.png", title: "click new campaign button failed", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-sidebar-campaigns.png", title: "click sidebar campaigns", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/contacts.png", title: "contacts", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/dashboard.png", title: "dashboard", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-articles.png", title: "helpcenter aaa articles", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-categories.png", title: "helpcenter aaa categories", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-locales.png", title: "helpcenter aaa locales", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-settings.png", title: "helpcenter aaa settings", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-portals.png", title: "helpcenter portals", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/mentions.png", title: "mentions", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-agent.png", title: "reports agent", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-conversation.png", title: "reports conversation", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-csat.png", title: "reports csat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-inboxes.png", title: "reports inboxes", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-label.png", title: "reports label", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-overview.png", title: "reports overview", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-teams.png", title: "reports teams", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/search.png", title: "search", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-account.png", title: "settings account", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-agents-list.png", title: "settings agents list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-auditlogs-list.png", title: "settings auditlogs list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-automation-list.png", title: "settings automation list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-canned-list.png", title: "settings canned list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-captain.png", title: "settings captain", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-custom-attributes.png", title: "settings custom attributes", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-custom-roles-list.png", title: "settings custom roles list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-inboxes-list.png", title: "settings inboxes list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-dashboard-apps.png", title: "settings integrations dashboard apps", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-linear.png", title: "settings integrations linear", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-notion.png", title: "settings integrations notion", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-shopify.png", title: "settings integrations shopify", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-slack.png", title: "settings integrations slack", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-webhook.png", title: "settings integrations webhook", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-labels-list.png", title: "settings labels list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-macros-list.png", title: "settings macros list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-profile.png", title: "settings profile", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-security.png", title: "settings security", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-sla-list.png", title: "settings sla list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-teams-list.png", title: "settings teams list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-working-hours-list.png", title: "settings working hours list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-busy.png", title: "sidekiq busy", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-cron.png", title: "sidekiq cron", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-dead.png", title: "sidekiq dead", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-home.png", title: "sidekiq home", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-queues.png", title: "sidekiq queues", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-retries.png", title: "sidekiq retries", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-scheduled.png", title: "sidekiq scheduled", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/unattended.png", title: "unattended", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/mentions.png", title: "mentions", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/notifications.png", title: "notifications", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-agent.png", title: "reports agent", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-conversation.png", title: "reports conversation", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-csat.png", title: "reports csat", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-inbox.png", title: "reports inbox", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-label.png", title: "reports label", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-sla.png", title: "reports sla", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-team.png", title: "reports team", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports.png", title: "reports", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/search.png", title: "search", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-account.png", title: "settings account", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-agent-bots.png", title: "settings agent bots", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-agents.png", title: "settings agents", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-assignment-policy.png", title: "settings assignment policy", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-attributes.png", title: "settings attributes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-audit-logs.png", title: "settings audit logs", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-automation.png", title: "settings automation", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-billing.png", title: "settings billing", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-canned.png", title: "settings canned", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-custom-roles.png", title: "settings custom roles", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-inboxes-new.png", title: "settings inboxes new", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-inboxes.png", title: "settings inboxes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-integrations.png", title: "settings integrations", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-labels.png", title: "settings labels", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-macros.png", title: "settings macros", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-profile.png", title: "settings profile", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-security.png", title: "settings security", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-teams.png", title: "settings teams", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/unattended.png", title: "unattended", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/local-register-onboarding.png", title: "local register onboarding", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/login.png", title: "login", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/register-onboarding.png", title: "register onboarding", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/accounts.png", title: "accounts", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/agent-bots.png", title: "agent bots", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/dashboard.png", title: "dashboard", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-busy.png", title: "sidekiq busy", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-cron.png", title: "sidekiq cron", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-dead.png", title: "sidekiq dead", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-home.png", title: "sidekiq home", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-queues.png", title: "sidekiq queues", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-retries.png", title: "sidekiq retries", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-scheduled.png", title: "sidekiq scheduled", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-access-tokens.png", title: "super admin access tokens", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-account-users-new.png", title: "super admin account users new", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs-edit-1.png", title: "super admin app configs edit 1", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs-new.png", title: "super admin app configs new", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs.png", title: "super admin app configs", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-logout.png", title: "super admin logout", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-response-documents.png", title: "super admin response documents", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-responses.png", title: "super admin responses", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-root.png", title: "super admin root", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/installation-configs.png", title: "installation configs", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/instance-status.png", title: "instance status", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-access-tokens.png", title: "super admin access tokens", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-account-users-new.png", title: "super admin account users new", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-accounts.png", title: "super admin accounts", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-agent-bots.png", title: "super admin agent bots", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-app-configs.png", title: "super admin app configs", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-dashboard.png", title: "super admin dashboard", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-home.png", title: "super admin home", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-installation-configs.png", title: "super admin installation configs", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-instance-status.png", title: "super admin instance status", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-platform-apps.png", title: "super admin platform apps", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-response-documents.png", title: "super admin response documents", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-responses.png", title: "super admin responses", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-root.png", title: "super admin root", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-settings.png", title: "super admin settings", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-users.png", title: "super admin users", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/platform-apps.png", title: "platform apps", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/settings.png", title: "settings", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/sidekiq.png", title: "sidekiq", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/users.png", title: "users", scope: "super-admin", group: "local" },
];

window.SCREENSHOT_DATA.push(
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-00-index.png", title: "captain faqs index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-01-create-modal-open.png", title: "captain faqs create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/documents-00-index.png", title: "captain documents index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-00-initial-full.png", title: "captain scenarios initial", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-01-after-add-all.png", title: "captain scenarios add all", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-02-search-refund.png", title: "captain scenarios search refund", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-04-create-modal-open.png", title: "captain scenarios create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-05-create-modal-filled.png", title: "captain scenarios create filled", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/playground-00-index.png", title: "captain playground index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/playground-01-input-filled.png", title: "captain playground input", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/inboxes-00-index.png", title: "captain inboxes index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-01-index-with-create.png", title: "captain tools index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-02-create-modal-open.png", title: "captain tools create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-03-create-modal-filled.png", title: "captain tools create filled", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/settings-00-index.png", title: "captain settings index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/settings-01-form-visible.png", title: "captain settings form visible", scope: "authenticated", group: "interactive" }
);

window.DOMAIN_DEEP_ANALYSIS = [
  {
    d: 'CONV',
    name: '会话中心（Conversation）',
    coreFlow: '接收消息 -> 分派/路由 -> 状态流转(open/pending/resolved/snoozed) -> SLA/报表统计',
    stateModel: '会话状态与优先级双状态机；toggle_status 有语义约束；last_seen 按小时节流',
    authz: 'admin 全量可见，agent 受 inbox/team 可见域限制',
    syncApi: '/api/v1/accounts/:id/conversations, /messages, /assignments',
    asyncJobs: '自动分配、SLA 计算、通知派发、统计聚合',
    migrationRisk: '状态机不一致会直接导致统计偏差和坐席工作流错乱',
    keyFiles: 'app/models/conversation.rb, app/policies/conversation_policy.rb, app/controllers/api/v1/accounts/conversations_controller.rb'
  },
  {
    d: 'INBOX',
    name: '渠道与收件箱（Inbox/Channel）',
    coreFlow: '渠道接入(web/email/whatsapp/...) -> inbox 配置 -> 对话归集 -> 成员协作',
    stateModel: 'inbox 类型驱动行为；active_bot 与 webhook 配置影响自动应答',
    authz: 'inbox 成员 + 管理员形成可分配集合',
    syncApi: '/api/v1/accounts/:id/inboxes, /inbox_members, channel-specific endpoints',
    asyncJobs: 'IMAP 拉取、渠道同步、Webhook 异步处理',
    migrationRisk: '渠道适配协议差异大，迁移中最易出现“可收不可发”或重复入站',
    keyFiles: 'app/models/inbox.rb, app/controllers/api/v1/accounts/inboxes_controller.rb'
  },
  {
    d: 'CRM',
    name: '联系人与客户资料（Contacts/CRM）',
    coreFlow: '联系人创建/合并/更新 -> 绑定会话 -> 标签/属性驱动分群',
    stateModel: 'visitor/lead/customer 类型 + email/phone/identifier 唯一性约束',
    authz: '导入导出、删除等高危操作管理员专属',
    syncApi: '/api/v1/accounts/:id/contacts, /contact_inboxes, /contact_filters',
    asyncJobs: '导入批处理、去重归并、事件派发',
    migrationRisk: '主键/唯一键策略改动会造成脏合并，影响历史会话归属',
    keyFiles: 'app/models/contact.rb, app/policies/contact_policy.rb'
  },
  {
    d: 'AUTO',
    name: '自动化与规则（Automation/Macro）',
    coreFlow: '条件命中 -> 执行动作 -> 会话/联系人侧效果落地',
    stateModel: '条件白名单 + 动作白名单 + query_operator(AND/OR) 校验',
    authz: 'Macro 存在 personal/global 可见域与作者权限模型',
    syncApi: '/api/v1/accounts/:id/automation_rules, /macros',
    asyncJobs: '计划任务触发、规则扫描、批量执行',
    migrationRisk: '规则语义不一致会造成“静默失效”且难被业务及时发现',
    keyFiles: 'app/models/automation_rule.rb, app/models/macro.rb, app/policies/macro_policy.rb'
  },
  {
    d: 'CMP',
    name: '营销活动（Campaign）',
    coreFlow: '活动配置 -> 触发匹配 -> 建会话/触发事件 -> 效果统计',
    stateModel: 'Website=ongoing; SMS/Whatsapp/Twilio=one_off',
    authz: '营销配置受账号与渠道能力限制',
    syncApi: '/api/v1/accounts/:id/campaigns, /api/v1/widget/campaigns',
    asyncJobs: '活动触发监听、消息发送、统计回填',
    migrationRisk: '触发窗口与防重策略迁移不一致会导致重复触达',
    keyFiles: 'app/models/campaign.rb, app/listeners/campaign_listener.rb'
  },
  {
    d: 'HC',
    name: '帮助中心（HelpCenter）',
    coreFlow: 'Portal -> Category -> Article 发布与多语言管理',
    stateModel: 'Article: draft/published/archived + locale 继承',
    authz: 'Portal 管理者与账号管理员权限分层',
    syncApi: '/api/v1/accounts/:id/portals, /categories, /articles',
    asyncJobs: '搜索索引更新、内容发布后缓存刷新',
    migrationRisk: 'slug/custom_domain 唯一性与路由映射迁移风险较高',
    keyFiles: 'app/models/portal.rb, app/models/article.rb'
  },
  {
    d: 'CAPTAIN',
    name: 'Captain AI（Assistants/FAQs/Documents/Tools）',
    coreFlow: '知识构建 -> Assistant 配置 -> Inbox 部署 -> 对话触发 AI 响应',
    stateModel: 'assistant_responses pending/approved 审核流 + scenario/tool 引用约束',
    authz: '管理员主导配置，agent 可使用 playground/certain runtime features',
    syncApi: '/api/v1/accounts/:id/captain/*',
    asyncJobs: '文档解析、向量更新、AI 任务与响应构建',
    migrationRisk: '模型调用、配额扣减、工具调用安全策略（SSRF）需行为等价',
    keyFiles: 'enterprise/app/controllers/api/v1/accounts/captain/*, app/javascript/dashboard/api/captain/*'
  },
  {
    d: 'ACL',
    name: '权限与多租户（RBAC/Policy）',
    coreFlow: '用户角色 -> Policy 判定 -> API/页面访问边界',
    stateModel: 'ApplicationPolicy 默认拒绝，按资源策略逐项放行',
    authz: 'account 维度隔离 + role 维度能力裁剪',
    syncApi: '全域 API 都受 policy gate 影响',
    asyncJobs: '审计日志、敏感操作记录',
    migrationRisk: '权限判断偏差会导致越权或误拒，属于高风险迁移项',
    keyFiles: 'app/policies/application_policy.rb, app/policies/*'
  },
  {
    d: 'ASYNC',
    name: '异步与调度（Sidekiq/Cron）',
    coreFlow: '定时触发 -> Job 入队 -> 重试/死信 -> 业务补偿',
    stateModel: 'schedule.yml 里有 1min/5min/15min/30min 多节奏任务',
    authz: '系统级任务，不直接暴露给业务角色',
    syncApi: 'Sidekiq Web + 任务触发链路',
    asyncJobs: 'trigger_scheduled_items, trigger_imap_email_inboxes, auto_assignment, cleanup',
    migrationRisk: 'Java 迁移时需保证幂等、重试策略、任务粒度与时钟一致',
    keyFiles: 'config/schedule.yml, app/jobs/**/*'
  }
];

window.FEATURE_DATA.push(
  { d:'CAPTAIN', id:'CAP-D01', f:'FAQ 审核状态机', r:'/api/v1/accounts/:id/captain/assistant_responses', rule:'pending/approved 双列表切换必须一致', fe:'app/javascript/dashboard/api/captain/response.js', be:'enterprise/app/controllers/api/v1/accounts/captain/assistant_responses_controller.rb' },
  { d:'CAPTAIN', id:'CAP-D02', f:'文档导入与索引', r:'/api/v1/accounts/:id/captain/documents', rule:'文档创建后可被 FAQ 关联检索', fe:'app/javascript/dashboard/api/captain/document.js', be:'enterprise/app/controllers/api/v1/accounts/captain/documents_controller.rb' },
  { d:'CAPTAIN', id:'CAP-D03', f:'Scenario 新建与建议场景', r:'/api/v1/accounts/:id/captain/assistants/:assistant_id/scenarios', rule:'Add all 与手工创建均落入同一场景集合', fe:'app/javascript/dashboard/api/captain/scenarios.js', be:'enterprise/app/controllers/api/v1/accounts/captain/scenarios_controller.rb' },
  { d:'CAPTAIN', id:'CAP-D04', f:'Custom Tool 创建', r:'/api/v1/accounts/:id/captain/custom_tools', rule:'method/auth/parameters 字段组合需可持久化', fe:'app/javascript/dashboard/api/captain/customTools.js', be:'enterprise/app/controllers/api/v1/accounts/captain/custom_tools_controller.rb' },
  { d:'CAPTAIN', id:'CAP-D05', f:'Inbox 绑定助手', r:'/api/v1/accounts/:id/captain/assistants/:assistant_id/inboxes', rule:'同一 inbox 仅能绑定单 assistant', fe:'app/javascript/dashboard/api/captain/inboxes.js', be:'enterprise/app/controllers/api/v1/accounts/captain/inboxes_controller.rb' },
  { d:'CAPTAIN', id:'CAP-D06', f:'设置与偏好', r:'/api/v1/accounts/:id/captain/preferences', rule:'模型与开关配置需即时生效', fe:'app/javascript/dashboard/api/captain/preferences.js', be:'config/routes.rb:59' },
  { d:'ASYNC', id:'ASYNC-D05', f:'Captain 文档异步处理', r:'captain documents jobs', rule:'导入 -> 解析 -> 响应构建链路需幂等', fe:'N/A', be:'enterprise/app/controllers/api/v1/accounts/captain/documents_controller.rb' },
  { d:'ACL', id:'ACL-D04', f:'Captain 管理权限', r:'captain controller actions', rule:'配置类动作应限制 admin；运行态动作支持 agent 范围', fe:'app/javascript/dashboard/routes/dashboard/captain/captain.routes.js', be:'enterprise/app/controllers/api/v1/accounts/captain/assistants_controller.rb' }
);

window.DOMAIN_ASSERTIONS = [
  { d:'CONV', id:'CONV-A01', sev:'high', scenario:'会话状态切换', given:'会话处于 pending', when:'执行 toggle_status', then:'状态变为 open 且列表归位', api:'POST /api/v1/accounts/:id/conversations/:id/toggle_status', fe:'conversation store', be:'app/models/conversation.rb' },
  { d:'CONV', id:'CONV-A02', sev:'mid', scenario:'优先级更新', given:'会话存在', when:'优先级改为 urgent', then:'列表与详情优先级一致', api:'PATCH /api/v1/accounts/:id/conversations/:id', fe:'conversation header UI', be:'app/models/conversation.rb' },
  { d:'CONV', id:'CONV-A03', sev:'high', scenario:'可见域限制', given:'agent 不在 inbox/team', when:'访问会话详情', then:'返回拒绝或不可见', api:'GET /api/v1/accounts/:id/conversations/:id', fe:'conversation route guard', be:'app/policies/conversation_policy.rb' },
  { d:'INBOX', id:'INBOX-A01', sev:'high', scenario:'渠道创建', given:'账号管理员', when:'创建新 inbox', then:'成员、渠道配置和 webhook 均持久化', api:'POST /api/v1/accounts/:id/inboxes', fe:'settings inbox forms', be:'app/controllers/api/v1/accounts/inboxes_controller.rb' },
  { d:'INBOX', id:'INBOX-A02', sev:'mid', scenario:'成员分配', given:'存在 inbox 与坐席', when:'添加成员', then:'会话分配列表立即可选', api:'POST /api/v1/accounts/:id/inbox_members', fe:'inbox members UI', be:'app/models/inbox.rb' },
  { d:'INBOX', id:'INBOX-A03', sev:'high', scenario:'IMAP 拉取链路', given:'邮箱渠道已配置', when:'调度任务触发', then:'邮件转入会话且不重复', api:'background jobs', fe:'N/A', be:'config/schedule.yml' },
  { d:'CRM', id:'CRM-A01', sev:'high', scenario:'联系人唯一性', given:'已有 email 联系人', when:'再创建同 email', then:'触发冲突策略而非重复记录', api:'POST /api/v1/accounts/:id/contacts', fe:'contacts create form', be:'app/models/contact.rb' },
  { d:'CRM', id:'CRM-A02', sev:'mid', scenario:'联系人属性更新', given:'联系人存在', when:'更新自定义属性', then:'列表筛选与详情一致', api:'PATCH /api/v1/accounts/:id/contacts/:id', fe:'contact profile panel', be:'app/models/contact.rb' },
  { d:'CRM', id:'CRM-A03', sev:'high', scenario:'高危操作限权', given:'非管理员用户', when:'执行导出/删除', then:'请求被拒绝', api:'DELETE/EXPORT contacts', fe:'contacts actions', be:'app/policies/contact_policy.rb' },
  { d:'AUTO', id:'AUTO-A01', sev:'high', scenario:'条件校验', given:'新建自动化规则', when:'query_operator 非 AND/OR', then:'保存失败并提示', api:'POST /api/v1/accounts/:id/automation_rules', fe:'automation builder', be:'app/models/automation_rule.rb' },
  { d:'AUTO', id:'AUTO-A02', sev:'mid', scenario:'动作白名单', given:'规则动作配置', when:'动作不在白名单', then:'后端拒绝', api:'POST /api/v1/accounts/:id/automation_rules', fe:'automation action picker', be:'app/models/automation_rule.rb' },
  { d:'AUTO', id:'AUTO-A03', sev:'mid', scenario:'宏权限', given:'personal macro', when:'其他 agent 访问', then:'仅作者或管理员可操作', api:'GET /api/v1/accounts/:id/macros', fe:'macros list', be:'app/policies/macro_policy.rb' },
  { d:'CMP', id:'CMP-A01', sev:'high', scenario:'活动类型推导', given:'Website 活动', when:'创建保存', then:'campaign_type=ongoing', api:'POST /api/v1/accounts/:id/campaigns', fe:'campaign form', be:'app/models/campaign.rb' },
  { d:'CMP', id:'CMP-A02', sev:'high', scenario:'URL 校验', given:'Website 活动 URL 非 http/https', when:'提交', then:'保存失败', api:'POST /api/v1/accounts/:id/campaigns', fe:'campaign form validation', be:'app/models/campaign.rb' },
  { d:'CMP', id:'CMP-A03', sev:'mid', scenario:'触发防重', given:'命中同活动条件', when:'重复访问页面', then:'不会重复创建过量会话', api:'/api/v1/widget/campaigns', fe:'widget trigger', be:'app/listeners/campaign_listener.rb' },
  { d:'HC', id:'HC-A01', sev:'high', scenario:'Portal 唯一性', given:'已有 slug', when:'创建同 slug portal', then:'保存失败', api:'POST /api/v1/accounts/:id/portals', fe:'help center portal form', be:'app/models/portal.rb' },
  { d:'HC', id:'HC-A02', sev:'mid', scenario:'文章状态流转', given:'draft 文章', when:'发布后再归档', then:'状态按 draft->published->archived 流转', api:'PATCH /api/v1/accounts/:id/articles/:id', fe:'article editor', be:'app/models/article.rb' },
  { d:'HC', id:'HC-A03', sev:'mid', scenario:'多语言继承', given:'portal 默认语言', when:'新建文章未指定 locale', then:'使用 portal locale', api:'POST /api/v1/accounts/:id/articles', fe:'article create', be:'app/models/article.rb' },
  { d:'CAPTAIN', id:'CAP-A01', sev:'high', scenario:'FAQ 状态切换', given:'存在 pending FAQ', when:'切换到 approved 视图', then:'两侧数量与条目一致', api:'GET /api/v1/accounts/:id/captain/assistant_responses?status=*', fe:'captain responses page', be:'enterprise/app/controllers/api/v1/accounts/captain/assistant_responses_controller.rb' },
  { d:'CAPTAIN', id:'CAP-A02', sev:'high', scenario:'文档导入', given:'填写 URL 或文档', when:'创建 document', then:'文档可见且可触发相关 FAQ 查询', api:'POST /api/v1/accounts/:id/captain/documents', fe:'captain documents page', be:'enterprise/app/controllers/api/v1/accounts/captain/documents_controller.rb' },
  { d:'CAPTAIN', id:'CAP-A03', sev:'high', scenario:'Scenario Add all', given:'推荐场景存在', when:'点击 Add all', then:'新增多条 scenario 并可搜索', api:'POST /api/v1/accounts/:id/captain/assistants/:assistant_id/scenarios', fe:'captain scenarios page', be:'enterprise/app/controllers/api/v1/accounts/captain/scenarios_controller.rb' },
  { d:'CAPTAIN', id:'CAP-A04', sev:'high', scenario:'Custom Tool 表单组合', given:'填写 method/auth/parameter', when:'提交创建', then:'后端持久化并可在 scenario 引用', api:'POST /api/v1/accounts/:id/captain/custom_tools', fe:'captain tools page', be:'enterprise/app/controllers/api/v1/accounts/captain/custom_tools_controller.rb' },
  { d:'CAPTAIN', id:'CAP-A05', sev:'high', scenario:'Inbox 绑定限制', given:'inbox 已绑定 assistant A', when:'再次绑定 assistant B', then:'被唯一约束阻止', api:'POST /api/v1/accounts/:id/captain/assistants/:assistant_id/inboxes', fe:'captain inboxes page', be:'enterprise/app/controllers/api/v1/accounts/captain/inboxes_controller.rb' },
  { d:'ACL', id:'ACL-A01', sev:'high', scenario:'默认拒绝', given:'未显式放行动作', when:'调用策略动作', then:'create/update/destroy 默认 false', api:'all APIs', fe:'N/A', be:'app/policies/application_policy.rb' },
  { d:'ACL', id:'ACL-A02', sev:'high', scenario:'资源级策略', given:'agent 角色', when:'访问超权限资源', then:'返回拒绝', api:'policy protected endpoints', fe:'route guards', be:'app/policies/*' },
  { d:'ACL', id:'ACL-A03', sev:'mid', scenario:'自定义角色', given:'配置自定义角色能力', when:'用户切换角色', then:'菜单/API 能力同步变化', api:'settings roles APIs', fe:'settings custom roles', be:'policy + role models' },
  { d:'ASYNC', id:'ASYNC-A01', sev:'high', scenario:'计划任务节奏', given:'schedule 已加载', when:'系统运行', then:'1min/5min/15min/30min 任务按节奏触发', api:'N/A', fe:'N/A', be:'config/schedule.yml' },
  { d:'ASYNC', id:'ASYNC-A02', sev:'high', scenario:'失败重试', given:'任务执行异常', when:'重试机制触发', then:'任务可重入且不产生重复副作用', api:'N/A', fe:'N/A', be:'sidekiq retry workflow' },
  { d:'ASYNC', id:'ASYNC-A03', sev:'mid', scenario:'Sidekiq 可观测性', given:'后台任务运行', when:'查看 Sidekiq 面板', then:'queues/retries/dead 指标可追踪', api:'/sidekiq', fe:'sidekiq web', be:'sidekiq web mount' }
];

window.HUMAN_TEST_CASES = [
  { id:'CONV-T01', d:'CONV', title:'待处理会话恢复为打开', type:'happy', priority:'P0', pre:'已有 pending 会话且当前用户可见', steps:['进入会话列表并定位 pending 标签页','打开目标会话','点击状态切换按钮','返回列表观察会话位置'], expectUI:'会话从 pending 移到 open，详情头部状态同步', expectAPI:'POST /api/v1/accounts/:id/conversations/:id/toggle_status', expectData:'conversation.status 从 pending 改为 open', expectJobs:'无强依赖任务', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/unattended.png' },
  { id:'CONV-T02', d:'CONV', title:'已解决会话重新打开', type:'boundary', priority:'P1', pre:'会话处于 resolved', steps:['进入 resolved 列表','打开会话','点击重新打开','检查时间线无重复系统消息'], expectUI:'状态变 open 且只出现一次状态变更记录', expectAPI:'POST /api/v1/accounts/:id/conversations/:id/toggle_status', expectData:'status 仅一次更新', expectJobs:'统计聚合任务会在周期任务中更新', evidence:'' },
  { id:'CONV-T03', d:'CONV', title:'优先级调到 urgent', type:'happy', priority:'P1', pre:'会话存在，用户有编辑权限', steps:['进入会话详情','展开优先级选择器','选择 urgent','刷新页面确认'], expectUI:'详情与列表都显示 urgent', expectAPI:'PATCH /api/v1/accounts/:id/conversations/:id', expectData:'priority=urgent', expectJobs:'报表聚合延迟更新', evidence:'' },
  { id:'CONV-T04', d:'CONV', title:'跨权限访问会话被拒绝', type:'permission', priority:'P0', pre:'agent 不属于目标 inbox/team', steps:['直接访问会话详情 URL','观察返回','检查菜单是否暴露会话'], expectUI:'提示无权限或跳转空状态', expectAPI:'GET /api/v1/accounts/:id/conversations/:id -> 403/404', expectData:'无数据变更', expectJobs:'无', evidence:'' },
  { id:'CONV-T05', d:'CONV', title:'last_seen 节流验证', type:'boundary', priority:'P2', pre:'会话无未读消息', steps:['连续进入同一会话多次','抓包 update_last_seen 调用','等待超过一小时再访问一次'], expectUI:'界面无异常闪动', expectAPI:'POST update_last_seen 触发频次受限', expectData:'last_seen_at 不会高频写入', expectJobs:'无', evidence:'' },

  { id:'INBOX-T01', d:'INBOX', title:'创建 Website Inbox', type:'happy', priority:'P0', pre:'管理员账号登录', steps:['进入设置-Inboxes','选择 Website 并填写必要字段','保存并返回列表','进入详情复查 token/webhook 配置'], expectUI:'列表出现新 inbox 且状态可用', expectAPI:'POST /api/v1/accounts/:id/inboxes', expectData:'inboxes/inbox_members/channel 配置写入', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-inboxes-new.png' },
  { id:'INBOX-T02', d:'INBOX', title:'新增 inbox 成员', type:'happy', priority:'P1', pre:'已有 inbox 与坐席', steps:['进入 inbox 成员管理','添加坐席 A','保存','在会话分配弹窗检查可选项'], expectUI:'坐席 A 出现在可分配列表', expectAPI:'POST /api/v1/accounts/:id/inbox_members', expectData:'inbox_members 新增关系', expectJobs:'无', evidence:'' },
  { id:'INBOX-T03', d:'INBOX', title:'移除 inbox 成员', type:'boundary', priority:'P1', pre:'inbox 已有多个成员', steps:['删除成员 B','返回会话详情尝试分配 B','刷新后再次检查'], expectUI:'B 不再可分配', expectAPI:'DELETE /api/v1/accounts/:id/inbox_members/:id', expectData:'关系删除', expectJobs:'无', evidence:'' },
  { id:'INBOX-T04', d:'INBOX', title:'IMAP 拉取无重复', type:'failure', priority:'P0', pre:'邮箱 inbox 已联通且有新邮件', steps:['观察 Sidekiq 调度触发','等待邮件入站','重复触发一次调度','检查是否重复创建会话'], expectUI:'只生成一条对应会话', expectAPI:'后台 job 拉取链路', expectData:'message 唯一入库', expectJobs:'TriggerImapEmailInboxesJob', evidence:'' },

  { id:'CRM-T01', d:'CRM', title:'同邮箱联系人防重复', type:'boundary', priority:'P0', pre:'已存在 email=foo@example.com 联系人', steps:['再次创建同邮箱联系人','提交表单','观察提示'], expectUI:'提示冲突或合并，不产生两条记录', expectAPI:'POST /api/v1/accounts/:id/contacts', expectData:'contacts 仍唯一', expectJobs:'无', evidence:'' },
  { id:'CRM-T02', d:'CRM', title:'联系人属性筛选一致性', type:'happy', priority:'P1', pre:'联系人已存在', steps:['更新自定义属性 segment=vip','回到列表按 segment 过滤','打开详情核对'], expectUI:'过滤结果与详情一致', expectAPI:'PATCH /api/v1/accounts/:id/contacts/:id', expectData:'custom_attributes 持久化', expectJobs:'无', evidence:'' },
  { id:'CRM-T03', d:'CRM', title:'非管理员导出联系人被拒绝', type:'permission', priority:'P0', pre:'agent 账号登录', steps:['进入 contacts','尝试导出或调用导出 API','观察错误'], expectUI:'按钮不可见或操作失败提示', expectAPI:'导出端点返回 403', expectData:'无', expectJobs:'无', evidence:'' },
  { id:'CRM-T04', d:'CRM', title:'删除联系人后的会话关联', type:'failure', priority:'P1', pre:'联系人绑定多个会话', steps:['删除联系人','打开历史会话','查看会话侧联系人展示'], expectUI:'会话仍可访问，联系人显示降级策略正确', expectAPI:'DELETE /api/v1/accounts/:id/contacts/:id', expectData:'contact 删除，conversation 保留', expectJobs:'可能触发清理任务', evidence:'' },

  { id:'AUTO-T01', d:'AUTO', title:'非法 query_operator 拒绝保存', type:'failure', priority:'P0', pre:'进入自动化规则创建页', steps:['构造 query_operator=NOT','提交','观察后端响应'], expectUI:'表单报错且不保存', expectAPI:'POST /api/v1/accounts/:id/automation_rules -> 422', expectData:'无新规则', expectJobs:'无', evidence:'' },
  { id:'AUTO-T02', d:'AUTO', title:'规则命中后自动打标签', type:'happy', priority:'P1', pre:'存在规则: 新消息包含关键词则打标签 vip', steps:['发送命中消息','刷新会话侧边栏','检查标签'], expectUI:'标签自动出现', expectAPI:'规则执行链路', expectData:'conversation.labels 包含 vip', expectJobs:'规则扫描任务可能延迟', evidence:'' },
  { id:'AUTO-T03', d:'AUTO', title:'个人宏可见性', type:'permission', priority:'P1', pre:'A 创建 personal macro', steps:['B 登录同账号','打开 macros 列表','搜索该宏'], expectUI:'B 不可见该宏', expectAPI:'GET /api/v1/accounts/:id/macros', expectData:'仅作者范围', expectJobs:'无', evidence:'' },
  { id:'AUTO-T04', d:'AUTO', title:'全局宏编辑权限', type:'permission', priority:'P0', pre:'存在 global macro 由 admin 创建', steps:['agent 尝试编辑','提交','观察响应'], expectUI:'编辑入口禁用或失败提示', expectAPI:'PATCH /api/v1/accounts/:id/macros/:id -> 403', expectData:'macro 未变更', expectJobs:'无', evidence:'' },

  { id:'CMP-T01', d:'CMP', title:'Website 活动自动 ongoing', type:'happy', priority:'P0', pre:'进入创建 campaign 页面', steps:['选择 Website 类型','填写基础字段并保存','查看详情'], expectUI:'显示 ongoing', expectAPI:'POST /api/v1/accounts/:id/campaigns', expectData:'campaign_type=ongoing', expectJobs:'触发监听准备', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-03-form-fields.png' },
  { id:'CMP-T02', d:'CMP', title:'非法 URL 拒绝', type:'failure', priority:'P0', pre:'Website 活动创建页', steps:['填入 ftp://abc','保存','查看错误'], expectUI:'提示 URL 必须 http/https', expectAPI:'POST /api/v1/accounts/:id/campaigns -> 422', expectData:'无新 campaign', expectJobs:'无', evidence:'' },
  { id:'CMP-T03', d:'CMP', title:'短信活动类型 one_off', type:'happy', priority:'P1', pre:'已配置短信渠道', steps:['创建 SMS 活动','保存后查看类型','重复编辑保存'], expectUI:'类型保持 one_off', expectAPI:'POST/PATCH /api/v1/accounts/:id/campaigns', expectData:'campaign_type=one_off', expectJobs:'发送任务入队', evidence:'' },
  { id:'CMP-T04', d:'CMP', title:'Widget 触发防重', type:'boundary', priority:'P1', pre:'用户命中同一活动条件', steps:['同会话反复刷新页面','检查活动触发次数','检查会话创建数量'], expectUI:'触发次数受控', expectAPI:'GET /api/v1/widget/campaigns', expectData:'不会爆量建会话', expectJobs:'campaign listener', evidence:'' },

  { id:'HC-T01', d:'HC', title:'Portal slug 唯一性', type:'failure', priority:'P0', pre:'已有 slug=aaa portal', steps:['再创建 slug=aaa','提交','观察报错'], expectUI:'保存失败提示唯一冲突', expectAPI:'POST /api/v1/accounts/:id/portals -> 422', expectData:'无新增 portal', expectJobs:'无', evidence:'' },
  { id:'HC-T02', d:'HC', title:'文章状态流转完整性', type:'happy', priority:'P1', pre:'已创建 draft 文章', steps:['发布文章','再归档','刷新列表'], expectUI:'状态依次 draft->published->archived', expectAPI:'PATCH /api/v1/accounts/:id/articles/:id', expectData:'status 按枚举变化', expectJobs:'索引刷新任务', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-articles.png' },
  { id:'HC-T03', d:'HC', title:'默认 locale 继承', type:'boundary', priority:'P1', pre:'portal 默认 locale=en', steps:['创建文章不填 locale','保存后查看详情','检查 public 页面语言'], expectUI:'文章 locale 自动为 en', expectAPI:'POST /api/v1/accounts/:id/articles', expectData:'locale 继承 portal', expectJobs:'缓存刷新', evidence:'' },
  { id:'HC-T04', d:'HC', title:'删除分类下文章保护', type:'failure', priority:'P1', pre:'分类下存在文章', steps:['尝试删除该分类','观察系统提示','处理文章后再删'], expectUI:'首次删除被阻止或要求迁移文章', expectAPI:'DELETE /api/v1/accounts/:id/categories/:id', expectData:'避免孤儿文章', expectJobs:'无', evidence:'' },

  { id:'CAP-T01', d:'CAPTAIN', title:'FAQ pending/approved 一致性', type:'happy', priority:'P0', pre:'存在 FAQ 数据', steps:['切到 pending','切到 approved','对比数量和条目'], expectUI:'双列表一致且过滤正确', expectAPI:'GET /api/v1/accounts/:id/captain/assistant_responses?status=*', expectData:'状态筛选准确', expectJobs:'可能有 embedding 更新任务', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-00-index.png' },
  { id:'CAP-T02', d:'CAPTAIN', title:'新增 FAQ 表单校验', type:'failure', priority:'P1', pre:'打开 FAQ 创建弹窗', steps:['仅填问题不填答案','提交','观察错误'], expectUI:'提示必填项', expectAPI:'POST /api/v1/accounts/:id/captain/assistant_responses -> 422', expectData:'不创建记录', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-01-create-modal-open.png' },
  { id:'CAP-T03', d:'CAPTAIN', title:'文档导入可见性', type:'happy', priority:'P0', pre:'打开 Documents', steps:['创建 document','返回列表','刷新页面'], expectUI:'文档持续可见', expectAPI:'POST /api/v1/accounts/:id/captain/documents', expectData:'document 记录存在', expectJobs:'crawl/response builder job', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/documents-00-index.png' },
  { id:'CAP-T04', d:'CAPTAIN', title:'Scenarios Add all', type:'happy', priority:'P0', pre:'助手存在推荐场景', steps:['进入 Scenarios','点击 Add all','搜索关键词验证'], expectUI:'新增多条场景且可检索', expectAPI:'POST /api/v1/accounts/:id/captain/assistants/:assistant_id/scenarios', expectData:'scenario 数量增加', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-01-after-add-all.png' },
  { id:'CAP-T05', d:'CAPTAIN', title:'Scenarios 自定义创建', type:'happy', priority:'P1', pre:'打开创建场景弹窗', steps:['填写名称描述示例','提交','回到列表'], expectUI:'新场景可见', expectAPI:'POST /api/v1/accounts/:id/captain/assistants/:assistant_id/scenarios', expectData:'scenario 新增', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-05-create-modal-filled.png' },
  { id:'CAP-T06', d:'CAPTAIN', title:'Custom Tool 创建表单', type:'happy', priority:'P0', pre:'打开 Tools 创建弹窗', steps:['填 method/auth/parameters','提交创建','在列表确认'], expectUI:'工具创建成功且可编辑', expectAPI:'POST /api/v1/accounts/:id/captain/custom_tools', expectData:'custom_tools 新记录', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-03-create-modal-filled.png' },
  { id:'CAP-T07', d:'CAPTAIN', title:'Tool 安全策略(SSRF)验证', type:'failure', priority:'P0', pre:'具备自定义工具创建权限', steps:['填内网地址或非 https endpoint','提交','观察响应'], expectUI:'提示地址不合法/被拦截', expectAPI:'POST /api/v1/accounts/:id/captain/custom_tools -> 422/403', expectData:'不创建危险工具', expectJobs:'无', evidence:'' },
  { id:'CAP-T08', d:'CAPTAIN', title:'Inbox 绑定唯一约束', type:'permission', priority:'P0', pre:'inbox 已绑定助手 A', steps:['切到助手 B 的 inbox 绑定页','尝试绑定同 inbox','提交'], expectUI:'提示冲突', expectAPI:'POST /api/v1/accounts/:id/captain/assistants/:assistant_id/inboxes', expectData:'原绑定不被覆盖', expectJobs:'无', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/inboxes-00-index.png' },
  { id:'CAP-T09', d:'CAPTAIN', title:'Playground 结果稳定性', type:'boundary', priority:'P1', pre:'助手已配置知识', steps:['在 playground 连续发送同问题','对比响应结构','检查是否报错'], expectUI:'响应可返回且无前端崩溃', expectAPI:'assistants playground endpoints', expectData:'无持久化副作用', expectJobs:'可能触发模型请求计量', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/playground-01-input-filled.png' },

  { id:'ACL-T01', d:'ACL', title:'默认拒绝策略回归', type:'permission', priority:'P0', pre:'构造未显式放行行为', steps:['以低权限账号调用目标动作','检查响应码','确认无副作用'], expectUI:'禁用或错误提示', expectAPI:'策略保护端点返回 403', expectData:'无写入', expectJobs:'无', evidence:'' },
  { id:'ACL-T02', d:'ACL', title:'角色切换菜单能力同步', type:'happy', priority:'P1', pre:'存在 custom role', steps:['切换用户角色','刷新左侧菜单','尝试访问受限页面'], expectUI:'菜单与访问能力同步变化', expectAPI:'相关端点权限一致', expectData:'role 权限生效', expectJobs:'无', evidence:'' },
  { id:'ACL-T03', d:'ACL', title:'审计日志记录', type:'boundary', priority:'P1', pre:'管理员执行敏感操作', steps:['执行删除/配置修改','打开审计日志','核对记录字段'], expectUI:'日志中可检索到操作', expectAPI:'audit logs endpoints', expectData:'audit_logs 有新增', expectJobs:'日志写入任务/同步', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-audit-logs.png' },

  { id:'ASYNC-T01', d:'ASYNC', title:'每分钟任务节奏', type:'happy', priority:'P0', pre:'Sidekiq 与 cron 运行中', steps:['打开 Sidekiq scheduled','观察 1 分钟任务','等待下一轮触发'], expectUI:'任务周期稳定出现', expectAPI:'N/A', expectData:'任务执行计数增长', expectJobs:'TriggerImapEmailInboxesJob', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-scheduled.png' },
  { id:'ASYNC-T02', d:'ASYNC', title:'失败任务重试机制', type:'failure', priority:'P0', pre:'制造可重试失败任务', steps:['触发失败','查看 retries 队列','等待重试后复查'], expectUI:'retries 有记录且重试后状态变化', expectAPI:'N/A', expectData:'不产生重复脏数据', expectJobs:'sidekiq retry', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-retries.png' },
  { id:'ASYNC-T03', d:'ASYNC', title:'死信队列可追踪', type:'failure', priority:'P1', pre:'存在多次失败任务', steps:['打开 dead 队列','查看错误堆栈','执行重试或删除'], expectUI:'dead 列表可操作', expectAPI:'N/A', expectData:'任务状态可追踪', expectJobs:'dead workflow', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-dead.png' },

  { id:'AUTH-T01', d:'AUTH', title:'注册登录主流程', type:'happy', priority:'P0', pre:'系统允许注册', steps:['访问注册页并创建账号','完成邮箱/密码流程','登录进入 dashboard'], expectUI:'可进入主系统', expectAPI:'auth endpoints', expectData:'user/account 创建', expectJobs:'欢迎类异步任务可选', evidence:'/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/login.png' },
  { id:'AUTH-T02', d:'AUTH', title:'错误密码登录失败', type:'failure', priority:'P1', pre:'已有有效账号', steps:['输入错误密码登录','观察错误信息','再次输入正确密码'], expectUI:'失败提示后可成功登录', expectAPI:'session create endpoint', expectData:'失败不创建 session', expectJobs:'无', evidence:'' }
];
