window.FEATURE_DATA = [
  { d:'AUTH', id:'AUTH-01', f:'登录/登出/注册/重置', r:'/app/login + auth API', rule:'认证流程与多租户上下文切换', fe:'/app/javascript/v3/views/routes.js', be:'/config/routes.rb' },
  { d:'CONV', id:'CONV-D01', f:'会话状态与优先级枚举', r:'/api/v1/accounts/:id/conversations', rule:'status=open/resolved/pending/snoozed; priority=low/medium/high/urgent', fe:'/app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js', be:'/app/models/conversation.rb:75' },
  { d:'CONV', id:'CONV-D02', f:'新会话默认状态判定', r:'conversation create', rule:'blocked->resolved; active_bot->pending; campaign+bot->pending', fe:'/app/javascript/dashboard/routes/dashboard/conversation', be:'/app/models/conversation.rb:254' },
  { d:'CONV', id:'CONV-D03', f:'toggle_status 语义', r:'POST toggle_status', rule:'open<->resolved, pending/snoozed->open', fe:'/app/javascript/dashboard/store/modules/conversations', be:'/app/models/conversation.rb:149' },
  { d:'CONV', id:'CONV-D04', f:'last_seen 节流', r:'POST update_last_seen', rule:'无未读时按小时节流写入', fe:'/app/javascript/dashboard', be:'/app/controllers/api/v1/accounts/conversations_controller.rb:114' },
  { d:'CRM', id:'CRM-D01', f:'联系人类型与唯一性', r:'/api/v1/accounts/:id/contacts', rule:'visitor/lead/customer; email/phone/identifier 约束', fe:'/app/javascript/dashboard/routes/dashboard/contacts/routes.js', be:'/app/models/contact.rb:50' },
  { d:'CRM', id:'CRM-D02', f:'联系人事件派发', r:'contact lifecycle events', rule:'create/update/delete 均派发 dispatcher', fe:'/app/javascript/dashboard', be:'/app/models/contact.rb:235' },
  { d:'INBOX', id:'INBOX-D01', f:'渠道识别与行为', r:'/api/v1/accounts/:id/inboxes', rule:'web/api/email/sms/whatsapp/social 分型', fe:'/app/javascript/dashboard/routes/dashboard/settings/inbox/inbox.routes.js', be:'/app/models/inbox.rb:113' },
  { d:'INBOX', id:'INBOX-D02', f:'active_bot 判定', r:'conversation bootstrap', rule:'agent_bot_active 或 dialogflow hook enabled', fe:'/app/javascript/dashboard', be:'/app/models/inbox.rb:169' },
  { d:'INBOX', id:'INBOX-D03', f:'可分配坐席集合', r:'assignable agents', rule:'inbox members + account admins', fe:'/app/javascript/dashboard/components', be:'/app/models/inbox.rb:165' },
  { d:'AUTO', id:'AUTO-D01', f:'自动化条件白名单', r:'/api/v1/accounts/:id/automation_rules', rule:'conditions_attributes + 自定义属性', fe:'/app/javascript/dashboard/routes/dashboard/settings/automation', be:'/app/models/automation_rule.rb:37' },
  { d:'AUTO', id:'AUTO-D02', f:'自动化动作白名单', r:'automation actions', rule:'仅允许定义动作集合', fe:'/app/javascript/dashboard', be:'/app/models/automation_rule.rb:42' },
  { d:'AUTO', id:'AUTO-D03', f:'逻辑运算符校验', r:'automation conditions', rule:'query_operator 仅 AND/OR', fe:'/app/javascript/dashboard', be:'/app/models/automation_rule.rb:91' },
  { d:'AUTO', id:'AUTO-D04', f:'Macro 可见性与执行权限', r:'/api/v1/accounts/:id/macros', rule:'personal/global + author/admin 策略', fe:'/app/javascript/dashboard/routes/dashboard/settings/macros', be:'/app/models/macro.rb:29 + /app/policies/macro_policy.rb:10' },
  { d:'CMP', id:'CMP-D01', f:'Campaign 类型约束', r:'/api/v1/accounts/:id/campaigns', rule:'仅 Website/Twilio SMS/Sms/Whatsapp', fe:'/app/javascript/dashboard/routes/dashboard/campaigns/campaigns.routes.js', be:'/app/models/campaign.rb:81' },
  { d:'CMP', id:'CMP-D02', f:'ongoing/one_off 推导', r:'campaign create/update', rule:'Website=ongoing; SMS/Twilio/Whatsapp=one_off', fe:'/app/javascript/dashboard/components-next/Campaigns', be:'/app/models/campaign.rb:88' },
  { d:'CMP', id:'CMP-D03', f:'URL 校验规则', r:'live chat campaign', rule:'Website campaign URL 必须 http/https', fe:'/app/javascript/dashboard/components-next/Campaigns', be:'/app/models/campaign.rb:100' },
  { d:'CMP', id:'CMP-D04', f:'Widget 触发链路', r:'/api/v1/widget/campaigns + /events', rule:'曝光匹配后发 campaign.triggered 建会话', fe:'/app/javascript/widget/api/endPoints.js:79', be:'/app/listeners/campaign_listener.rb:2' },
  { d:'HC', id:'HC-D01', f:'Portal 基础约束', r:'/api/v1/accounts/:id/portals', rule:'name/slug/account 必填；slug/custom_domain 唯一', fe:'/app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js', be:'/app/models/portal.rb:39' },
  { d:'HC', id:'HC-D02', f:'Article 状态机与语言继承', r:'/api/v1/accounts/:id/articles', rule:'draft/published/archived + locale 继承', fe:'/app/javascript/dashboard/routes/dashboard/helpcenter', be:'/app/models/article.rb:67' },
  { d:'ACL', id:'ACL-D01', f:'默认拒绝策略', r:'all policies', rule:'ApplicationPolicy 默认 create/update/destroy=false', fe:'N/A', be:'/app/policies/application_policy.rb:12' },
  { d:'ACL', id:'ACL-D02', f:'会话可见范围', r:'conversation show/index', rule:'admin 全量；agent 需 inbox/team 访问', fe:'/app/javascript/dashboard', be:'/app/policies/conversation_policy.rb:10' },
  { d:'ACL', id:'ACL-D03', f:'联系人高危操作限权', r:'contact import/export/destroy', rule:'管理员专属', fe:'/app/javascript/dashboard/routes/dashboard/contacts', be:'/app/policies/contact_policy.rb:10' },
  { d:'ASYNC', id:'ASYNC-D01', f:'定时触发计划项', r:'trigger_scheduled_items_job', rule:'每 5 分钟执行', fe:'N/A', be:'/config/schedule.yml:11' },
  { d:'ASYNC', id:'ASYNC-D02', f:'IMAP 拉取任务', r:'trigger_imap_email_inboxes_job', rule:'每 1 分钟执行', fe:'N/A', be:'/config/schedule.yml:17' },
  { d:'ASYNC', id:'ASYNC-D03', f:'自动分配任务', r:'bulk_auto_assignment + periodic_assignment', rule:'每 15/30 分钟执行', fe:'N/A', be:'/config/schedule.yml:51' },
  { d:'ASYNC', id:'ASYNC-D04', f:'清理任务', r:'notification/orphan/stale cleanup', rule:'按 cron 执行运维清理', fe:'N/A', be:'/config/schedule.yml:24' }
];

window.SCREENSHOT_DATA = [
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/campaigns.png", title: "campaigns", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-assistants.png", title: "captain assistants", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-documents.png", title: "captain documents", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-guardrails.png", title: "captain guardrails", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-guidelines.png", title: "captain guidelines", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-inboxes.png", title: "captain inboxes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-playground.png", title: "captain playground", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-responses.png", title: "captain responses", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-scenarios.png", title: "captain scenarios", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-settings.png", title: "captain settings", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/captain-tools.png", title: "captain tools", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/contacts.png", title: "contacts", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-folder-filter.png", title: "conversation folder filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-inbox-filter.png", title: "conversation inbox filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-label-filter.png", title: "conversation label filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-participating.png", title: "conversation participating", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/conversation-team-filter.png", title: "conversation team filter", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/dashboard.png", title: "dashboard", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-01-list.png", title: "campaign livechat 01 list", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-02-created-list.png", title: "campaign livechat 02 created list", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-03-form-fields.png", title: "campaign livechat 03 form fields", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaign-livechat-list-before-create.png", title: "campaign livechat list before create", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-ongoing.png", title: "campaigns ongoing", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-sms.png", title: "campaigns sms", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/campaigns-whatsapp.png", title: "campaigns whatsapp", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/companies.png", title: "companies", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-articles.png", title: "helpcenter aaa articles", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-categories.png", title: "helpcenter aaa categories", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-locales.png", title: "helpcenter aaa locales", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-public-home.png", title: "helpcenter aaa public home", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/helpcenter-aaa-settings.png", title: "helpcenter aaa settings", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/reports-bot.png", title: "reports bot", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/reports-overview.png", title: "reports overview", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-canned-new.png", title: "settings canned new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-captain.png", title: "settings captain", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-conversation-workflow.png", title: "settings conversation workflow", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-inbox-show.png", title: "settings inbox show", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-dashboard-apps.png", title: "settings integrations dashboard apps", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-linear.png", title: "settings integrations linear", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-notion.png", title: "settings integrations notion", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-shopify.png", title: "settings integrations shopify", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-slack.png", title: "settings integrations slack", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-integrations-webhook.png", title: "settings integrations webhook", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-macros-new.png", title: "settings macros new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-profile-mfa.png", title: "settings profile mfa", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-sla.png", title: "settings sla", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/extended/settings-teams-new.png", title: "settings teams new", scope: "authenticated", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/help-center.png", title: "help center", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/inbox-view.png", title: "inbox view", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-livechat.png", title: "campaigns livechat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-ongoing.png", title: "campaigns ongoing", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-sms.png", title: "campaigns sms", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/campaigns-whatsapp.png", title: "campaigns whatsapp", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-livechat.png", title: "click campaign tab livechat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-sms.png", title: "click campaign tab sms", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-campaign-tab-whatsapp-failed.png", title: "click campaign tab whatsapp failed", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-new-campaign-button-failed.png", title: "click new campaign button failed", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/click-sidebar-campaigns.png", title: "click sidebar campaigns", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/contacts.png", title: "contacts", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/dashboard.png", title: "dashboard", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-articles.png", title: "helpcenter aaa articles", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-categories.png", title: "helpcenter aaa categories", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-locales.png", title: "helpcenter aaa locales", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-aaa-settings.png", title: "helpcenter aaa settings", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/helpcenter-portals.png", title: "helpcenter portals", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/mentions.png", title: "mentions", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-agent.png", title: "reports agent", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-conversation.png", title: "reports conversation", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-csat.png", title: "reports csat", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-inboxes.png", title: "reports inboxes", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-label.png", title: "reports label", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-overview.png", title: "reports overview", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/reports-teams.png", title: "reports teams", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/search.png", title: "search", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-account.png", title: "settings account", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-agents-list.png", title: "settings agents list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-auditlogs-list.png", title: "settings auditlogs list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-automation-list.png", title: "settings automation list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-canned-list.png", title: "settings canned list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-captain.png", title: "settings captain", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-custom-attributes.png", title: "settings custom attributes", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-custom-roles-list.png", title: "settings custom roles list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-inboxes-list.png", title: "settings inboxes list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-dashboard-apps.png", title: "settings integrations dashboard apps", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-linear.png", title: "settings integrations linear", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-notion.png", title: "settings integrations notion", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-shopify.png", title: "settings integrations shopify", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-slack.png", title: "settings integrations slack", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-integrations-webhook.png", title: "settings integrations webhook", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-labels-list.png", title: "settings labels list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-macros-list.png", title: "settings macros list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-profile.png", title: "settings profile", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-security.png", title: "settings security", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-sla-list.png", title: "settings sla list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-teams-list.png", title: "settings teams list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/settings-working-hours-list.png", title: "settings working hours list", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-busy.png", title: "sidekiq busy", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-cron.png", title: "sidekiq cron", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-dead.png", title: "sidekiq dead", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-home.png", title: "sidekiq home", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-queues.png", title: "sidekiq queues", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-retries.png", title: "sidekiq retries", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/sidekiq-scheduled.png", title: "sidekiq scheduled", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/link-sweep/unattended.png", title: "unattended", scope: "authenticated", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/mentions.png", title: "mentions", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/notifications.png", title: "notifications", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-agent.png", title: "reports agent", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-conversation.png", title: "reports conversation", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-csat.png", title: "reports csat", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-inbox.png", title: "reports inbox", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-label.png", title: "reports label", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-sla.png", title: "reports sla", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports-team.png", title: "reports team", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/reports.png", title: "reports", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/search.png", title: "search", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-account.png", title: "settings account", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-agent-bots.png", title: "settings agent bots", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-agents.png", title: "settings agents", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-assignment-policy.png", title: "settings assignment policy", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-attributes.png", title: "settings attributes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-audit-logs.png", title: "settings audit logs", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-automation.png", title: "settings automation", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-billing.png", title: "settings billing", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-canned.png", title: "settings canned", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-custom-roles.png", title: "settings custom roles", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-inboxes-new.png", title: "settings inboxes new", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-inboxes.png", title: "settings inboxes", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-integrations.png", title: "settings integrations", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-labels.png", title: "settings labels", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-macros.png", title: "settings macros", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-profile.png", title: "settings profile", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-security.png", title: "settings security", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/settings-teams.png", title: "settings teams", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/authenticated/unattended.png", title: "unattended", scope: "authenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/local-register-onboarding.png", title: "local register onboarding", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/login.png", title: "login", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/register-onboarding.png", title: "register onboarding", scope: "unauthenticated", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/accounts.png", title: "accounts", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/agent-bots.png", title: "agent bots", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/dashboard.png", title: "dashboard", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-busy.png", title: "sidekiq busy", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-cron.png", title: "sidekiq cron", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-dead.png", title: "sidekiq dead", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-home.png", title: "sidekiq home", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-queues.png", title: "sidekiq queues", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-retries.png", title: "sidekiq retries", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/sidekiq-scheduled.png", title: "sidekiq scheduled", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-access-tokens.png", title: "super admin access tokens", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-account-users-new.png", title: "super admin account users new", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs-edit-1.png", title: "super admin app configs edit 1", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs-new.png", title: "super admin app configs new", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-app-configs.png", title: "super admin app configs", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-logout.png", title: "super admin logout", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-response-documents.png", title: "super admin response documents", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-responses.png", title: "super admin responses", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/extended/super-admin-root.png", title: "super admin root", scope: "super-admin", group: "extended" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/installation-configs.png", title: "installation configs", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/instance-status.png", title: "instance status", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-access-tokens.png", title: "super admin access tokens", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-account-users-new.png", title: "super admin account users new", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-accounts.png", title: "super admin accounts", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-agent-bots.png", title: "super admin agent bots", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-app-configs.png", title: "super admin app configs", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-dashboard.png", title: "super admin dashboard", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-home.png", title: "super admin home", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-installation-configs.png", title: "super admin installation configs", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-instance-status.png", title: "super admin instance status", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-platform-apps.png", title: "super admin platform apps", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-response-documents.png", title: "super admin response documents", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-responses.png", title: "super admin responses", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-root.png", title: "super admin root", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-settings.png", title: "super admin settings", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/link-sweep/super-admin-users.png", title: "super admin users", scope: "super-admin", group: "link-sweep" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/platform-apps.png", title: "platform apps", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/settings.png", title: "settings", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/sidekiq.png", title: "sidekiq", scope: "super-admin", group: "local" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/local/super-admin/users.png", title: "users", scope: "super-admin", group: "local" },
];

window.SCREENSHOT_DATA.push(
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-00-index.png", title: "captain faqs index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/faqs-01-create-modal-open.png", title: "captain faqs create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/documents-00-index.png", title: "captain documents index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-00-initial-full.png", title: "captain scenarios initial", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-01-after-add-all.png", title: "captain scenarios add all", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-02-search-refund.png", title: "captain scenarios search refund", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-04-create-modal-open.png", title: "captain scenarios create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/scenarios-05-create-modal-filled.png", title: "captain scenarios create filled", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/playground-00-index.png", title: "captain playground index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/playground-01-input-filled.png", title: "captain playground input", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/inboxes-00-index.png", title: "captain inboxes index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-01-index-with-create.png", title: "captain tools index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-02-create-modal-open.png", title: "captain tools create modal", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/tools-03-create-modal-filled.png", title: "captain tools create filled", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/settings-00-index.png", title: "captain settings index", scope: "authenticated", group: "interactive" },
  { path: "/Users/wangqi/git/wangqi/chatwoot-wq/.codex/migration/screenshots/interactive/captain/settings-01-form-visible.png", title: "captain settings form visible", scope: "authenticated", group: "interactive" }
);
